//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HOADON
    {
        public int MaHD { get; set; }
        public string MaKH { get; set; }
        public string TenKH { get; set; }
        public string TongTien { get; set; }
        public Nullable<System.DateTime> NgayLapHD { get; set; }
    
        public virtual KHACHHANG KHACHHANG { get; set; }
        public virtual CHITIETHOADON CHITIETHOADON { get; set; }
    }
}
